// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebTickets.Infrastructure;

#nullable disable

namespace WebTickets.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebTickets.Domain.Module.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_file");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_file_message_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_file_ticket_id");

                    b.ToTable("File", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_message");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_message_author_id");

                    b.HasIndex("TicketId", "SentAt")
                        .HasDatabaseName("ix_message_ticket_id_sent_at");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("TagName")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_tag_name");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ticket");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.TicketTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_ticket_tag_tag_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_tag_ticket_id");

                    b.ToTable("TicketTag", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.PrimitiveCollection<string[]>("_permissions")
                        .HasColumnType("text[]")
                        .HasColumnName("Permissions");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_role_role_name");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("WebTickets.Domain.Module.User.User", b =>
                {
                    b.HasOne("WebTickets.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_id");
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.File", b =>
                {
                    b.HasOne("WebTickets.Domain.Modules.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_file_message_message_id");

                    b.HasOne("WebTickets.Domain.Modules.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_file_ticket_ticket_id");

                    b.Navigation("Message");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Message", b =>
                {
                    b.HasOne("WebTickets.Domain.Module.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_user_author_id");

                    b.HasOne("WebTickets.Domain.Modules.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_ticket_ticket_id");

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.TicketTag", b =>
                {
                    b.HasOne("WebTickets.Domain.Modules.Tag", "Tag")
                        .WithMany("TicketTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_tag_tag_tag_id");

                    b.HasOne("WebTickets.Domain.Modules.Ticket", "Ticket")
                        .WithMany("TicketTags")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_tag_ticket_ticket_id");

                    b.Navigation("Tag");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Tag", b =>
                {
                    b.Navigation("TicketTags");
                });

            modelBuilder.Entity("WebTickets.Domain.Modules.Ticket", b =>
                {
                    b.Navigation("TicketTags");
                });
#pragma warning restore 612, 618
        }
    }
}
