<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\WebTickets.Application\WebTickets.Application.csproj" />
      <ProjectReference Include="..\src\WebTickets.Domain\WebTickets.Domain.csproj" />
      <ProjectReference Include="..\src\WebTickets.Infrastructure\WebTickets.Infrastructure.csproj" />
    </ItemGroup>

</Project>
